name: Docker Image CI

on:
  push:
    branches: 
    - "master"
  pull_request:
    branches:
      - "master"

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/corenlp:test

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}

    - name: Test Docker Image
      run: |
          docker run --rm ${{ env.TEST_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/corenlp:latest